return {
  {
    "nvim-neo-tree/neo-tree.nvim",
    opts = {
      filesystem = {
        filtered_items = {
          hide_dotfiles = false,
          hide_gitignored = false,
          hide_by_name = {
            ".DS_Store",
            ".git",
            "Thumbs.db",
            "ehthumbs.db",
            ".vscode",
            ".idea",
            "node_modules",
            "npm-debug.log",
            "yarn-error.log",
            "__pycache__",
            ".bundle",
            "vendor",
            ".cache",
            "compile_commands.json",
          },
          hide_by_pattern = {
            "*.o",
            "*.d",
            "*.suo",
            "*.user",
            "*.userosscache",
            "*.sln.docstates",
            "*.py[cod]",
            "*.pyo",
            "*.pyd",
            "*venv*",
            "*.swp",
            "*.class",
            "*.jar",
            "*.war",
            "*.ear",
            "*.log",
            "*.gem",
            "*.rbc",
          },
        },
      },
      window = {
        width = 30,
      },
    },
  },
}
